### ISSUE TITLE
Abbility to see remote branches for checkout

### ISSUE THREAD

**Issue by jason-kerney** [cmstead/gittey#5]
When you initially clone a directory the command:

`gittey checkout` produces the following output:

> No Branches

Once you checkout a branch via git checkout command, then gittey can see that branch.

Instead, it would be nice if gittey would see the remote branches also.

**Comment by cmstead** [comment]
I updated the readme. There is a flag I added a long time ago but never documented:

`gittey checkout --remote`

I think this _should_ give you what you are looking for.
